name: Browser.Features

description: Browser features detector.

license: MIT-style license.

copyright: Copyright (c) 2010.

authors: 
  - Slik

provides: [Browser.Features]

requires: 
  - core/1.2.4: Browser
