name: Browser.Features

description: Browser features detector.

license: MIT-style license.

copyright: Copyright (c) 2010.

author: Slik (http://diveintoweb.net)

provides: [Browser.Features]

requires: 
  - core/1.2.4: Browser
